//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSD_Mobipay.Tests.BankOperationWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankOperationWS.IBankOperation")]
    public interface IBankOperation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankOperation/getUser", ReplyAction="http://tempuri.org/IBankOperation/getUserResponse")]
        DSD.BusinessEntity.UsuariosBE getUser(System.Nullable<System.Guid> gBanco, string xCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankOperation/getUser", ReplyAction="http://tempuri.org/IBankOperation/getUserResponse")]
        System.Threading.Tasks.Task<DSD.BusinessEntity.UsuariosBE> getUserAsync(System.Nullable<System.Guid> gBanco, string xCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankOperation/refillwallet", ReplyAction="http://tempuri.org/IBankOperation/refillwalletResponse")]
        DSD.BusinessEntity.MovimientosBE refillwallet(System.Nullable<System.Guid> gBanco, string xCodigoUsuario, string xOperacionBanco, decimal mMonto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankOperation/refillwallet", ReplyAction="http://tempuri.org/IBankOperation/refillwalletResponse")]
        System.Threading.Tasks.Task<DSD.BusinessEntity.MovimientosBE> refillwalletAsync(System.Nullable<System.Guid> gBanco, string xCodigoUsuario, string xOperacionBanco, decimal mMonto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankOperationChannel : DSD_Mobipay.Tests.BankOperationWS.IBankOperation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankOperationClient : System.ServiceModel.ClientBase<DSD_Mobipay.Tests.BankOperationWS.IBankOperation>, DSD_Mobipay.Tests.BankOperationWS.IBankOperation {
        
        public BankOperationClient() {
        }
        
        public BankOperationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankOperationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankOperationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankOperationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DSD.BusinessEntity.UsuariosBE getUser(System.Nullable<System.Guid> gBanco, string xCodigoUsuario) {
            return base.Channel.getUser(gBanco, xCodigoUsuario);
        }
        
        public System.Threading.Tasks.Task<DSD.BusinessEntity.UsuariosBE> getUserAsync(System.Nullable<System.Guid> gBanco, string xCodigoUsuario) {
            return base.Channel.getUserAsync(gBanco, xCodigoUsuario);
        }
        
        public DSD.BusinessEntity.MovimientosBE refillwallet(System.Nullable<System.Guid> gBanco, string xCodigoUsuario, string xOperacionBanco, decimal mMonto) {
            return base.Channel.refillwallet(gBanco, xCodigoUsuario, xOperacionBanco, mMonto);
        }
        
        public System.Threading.Tasks.Task<DSD.BusinessEntity.MovimientosBE> refillwalletAsync(System.Nullable<System.Guid> gBanco, string xCodigoUsuario, string xOperacionBanco, decimal mMonto) {
            return base.Channel.refillwalletAsync(gBanco, xCodigoUsuario, xOperacionBanco, mMonto);
        }
    }
}
