//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSD_Mobipay.wsBankOperation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MensajesBE", Namespace="http://schemas.datacontract.org/2004/07/DSD.BusinessEntity")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSD_Mobipay.wsBankOperation.MovimientosBE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DSD_Mobipay.wsBankOperation.UsuariosBE))]
    public partial class MensajesBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool lErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xMensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool lError {
            get {
                return this.lErrorField;
            }
            set {
                if ((this.lErrorField.Equals(value) != true)) {
                    this.lErrorField = value;
                    this.RaisePropertyChanged("lError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xMensaje {
            get {
                return this.xMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.xMensajeField, value) != true)) {
                    this.xMensajeField = value;
                    this.RaisePropertyChanged("xMensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xRespuesta {
            get {
                return this.xRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.xRespuestaField, value) != true)) {
                    this.xRespuestaField = value;
                    this.RaisePropertyChanged("xRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MovimientosBE", Namespace="http://schemas.datacontract.org/2004/07/DSD.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class MovimientosBE : DSD_Mobipay.wsBankOperation.MensajesBE {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuariosBE", Namespace="http://schemas.datacontract.org/2004/07/DSD.BusinessEntity")]
    [System.SerializableAttribute()]
    public partial class UsuariosBE : DSD_Mobipay.wsBankOperation.MensajesBE {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> gUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iRolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xNombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xUsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> gUsuario {
            get {
                return this.gUsuarioField;
            }
            set {
                if ((this.gUsuarioField.Equals(value) != true)) {
                    this.gUsuarioField = value;
                    this.RaisePropertyChanged("gUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iRol {
            get {
                return this.iRolField;
            }
            set {
                if ((this.iRolField.Equals(value) != true)) {
                    this.iRolField = value;
                    this.RaisePropertyChanged("iRol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xApellidos {
            get {
                return this.xApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.xApellidosField, value) != true)) {
                    this.xApellidosField = value;
                    this.RaisePropertyChanged("xApellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xDocumento {
            get {
                return this.xDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.xDocumentoField, value) != true)) {
                    this.xDocumentoField = value;
                    this.RaisePropertyChanged("xDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xNombres {
            get {
                return this.xNombresField;
            }
            set {
                if ((object.ReferenceEquals(this.xNombresField, value) != true)) {
                    this.xNombresField = value;
                    this.RaisePropertyChanged("xNombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xUsuario {
            get {
                return this.xUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.xUsuarioField, value) != true)) {
                    this.xUsuarioField = value;
                    this.RaisePropertyChanged("xUsuario");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsBankOperation.IBankOperation")]
    public interface IBankOperation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankOperation/getUser", ReplyAction="http://tempuri.org/IBankOperation/getUserResponse")]
        DSD_Mobipay.wsBankOperation.UsuariosBE getUser(System.Nullable<System.Guid> gBanco, string xCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankOperation/getUser", ReplyAction="http://tempuri.org/IBankOperation/getUserResponse")]
        System.Threading.Tasks.Task<DSD_Mobipay.wsBankOperation.UsuariosBE> getUserAsync(System.Nullable<System.Guid> gBanco, string xCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankOperation/refillwallet", ReplyAction="http://tempuri.org/IBankOperation/refillwalletResponse")]
        DSD_Mobipay.wsBankOperation.MovimientosBE refillwallet(System.Nullable<System.Guid> gBanco, string xCodigoUsuario, string xOperacionBanco, decimal mMonto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankOperation/refillwallet", ReplyAction="http://tempuri.org/IBankOperation/refillwalletResponse")]
        System.Threading.Tasks.Task<DSD_Mobipay.wsBankOperation.MovimientosBE> refillwalletAsync(System.Nullable<System.Guid> gBanco, string xCodigoUsuario, string xOperacionBanco, decimal mMonto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankOperationChannel : DSD_Mobipay.wsBankOperation.IBankOperation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankOperationClient : System.ServiceModel.ClientBase<DSD_Mobipay.wsBankOperation.IBankOperation>, DSD_Mobipay.wsBankOperation.IBankOperation {
        
        public BankOperationClient() {
        }
        
        public BankOperationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankOperationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankOperationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankOperationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DSD_Mobipay.wsBankOperation.UsuariosBE getUser(System.Nullable<System.Guid> gBanco, string xCodigoUsuario) {
            return base.Channel.getUser(gBanco, xCodigoUsuario);
        }
        
        public System.Threading.Tasks.Task<DSD_Mobipay.wsBankOperation.UsuariosBE> getUserAsync(System.Nullable<System.Guid> gBanco, string xCodigoUsuario) {
            return base.Channel.getUserAsync(gBanco, xCodigoUsuario);
        }
        
        public DSD_Mobipay.wsBankOperation.MovimientosBE refillwallet(System.Nullable<System.Guid> gBanco, string xCodigoUsuario, string xOperacionBanco, decimal mMonto) {
            return base.Channel.refillwallet(gBanco, xCodigoUsuario, xOperacionBanco, mMonto);
        }
        
        public System.Threading.Tasks.Task<DSD_Mobipay.wsBankOperation.MovimientosBE> refillwalletAsync(System.Nullable<System.Guid> gBanco, string xCodigoUsuario, string xOperacionBanco, decimal mMonto) {
            return base.Channel.refillwalletAsync(gBanco, xCodigoUsuario, xOperacionBanco, mMonto);
        }
    }
}
